version: "3"

vars:
  include: ./include
  build: ./build
  test: ./test

tasks:
  init:
    vars:
      template: 'templates/{{ .CLI_ARGS | default "header" }}.cpp'
    preconditions:
      - sh: "[ -f {{ .template }} ]"
        msg: "{{ .template }} が存在しません。"
    cmds:
      - rm -rf {{ .include }}
      - git clone --branch master --depth 1 --no-progress https://github.com/atcoder/ac-library.git {{ .include }}
      - mkdir -p {{ .test }}
      - cp {{ .template }} main.cpp
      - cmd: cmake -B {{ .build }} -S . -DCMAKE_BUILD_TYPE=Debug -G 'MinGW Makefiles' -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON
        platforms:
          - windows
      - cmd: cmake -B {{ .build }} -S . -DCMAKE_BUILD_TYPE=Debug -G 'Unix Makefiles' -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON
        platforms:
          - linux

  build:
    cmds:
      - cmake --build {{ .build }}

  default:
    aliases:
      - run
    deps:
      - task: build
    vars:
      inputs:
        sh: ls {{ .test }}/
    cmds:
      - for:
          var: inputs
          as: input
        cmd: cat {{ .test }}/{{ .input | replace "\\" "/" }} | ./build/main{{ exeExt }}
